alexpate/awesome-design-systems

- README.md
> Google Material Design

- README.md
Added blueprint ui kit. Blueprint is a React UI Kit. Also includes [sketch assets](http://blueprintjs.com/docs/#core/resources.sketch-assets)
> added blueprint js ui toolkit to readme

- README.md
Yelp link contains pattern library, color library, icon library, mobile
pattern library, and brand/voice styleguide.
> Add Yelp Styleguide

- README.md
Added the 'Voice and Tone' icon to IBM Carbon on the list, as we have this in our system 😄 
You can find it [here](http://carbondesignsystem.com/guidelines/content/general).
> Add 'Voice and Tone' icon to IBM Carbon

- README.md
- Added GitHub's Primer UI library
- Added BuzzFeed's Solid UI library
> Adding Primer & Solid

- README.md
Looks very much alike with Google Material Design
> Add Ant Design by Alibaba

- README.md
add Patternfly Open Interface Project
> Add Patternfly Interface Project

- README.md
https://github.com/alexpate/awesome-design-systems/issues/15
> Add Apple guidelines

- README.md
> Add BBC GEL (Global Experience Language)

- README.md
Audi Ui Kit is a interface design system within the renewed Audi Brand Guidelines.
> Added Audi UI Kit

- README.md
Great Collection! Wanted to add a thumbs up for the Clarity design system designer kit. Please let me know if the change looks okay.
Designer Kit Link: https://vmware.github.io/clarity/get-started#designResources
> Clarity Design System - Designer Kit

- README.md
Files can be found here: https://standards.usa.gov/getting-started/designers/
> U.S. Web Design Standards do provide design files

- README.md
Add :+1: for designer kit for Patternfly
Patternfly is providing a designer kit on: https://github.com/patternfly/patternfly-design/tree/master/resources/templates
> Update "Designer Kit" for patternfly

- README.md
Design guidelines for IBM.com website. Voice & Tone is currently a bit broken on the website, but it's there.
> Added IBM Northstar Web Standards

- README.md
https://github.com/alexpate/awesome-design-systems/issues/43
> Add basic definition

- README.md
I found this page while I was browsing on The University of Melbourne's website today. It's interested to see that design systems aren't only used in tech organizations, but also in academic organizations. Here's the link to the design system: https://web.unimelb.edu.au/.
> Added The University of Melbourne Design System

- README.md
Added GOV.UK Service Manual
Added NHS.UK Service Manual (Alpha)
> Added New links

- README.md
Added Nachos - Trello's design system.
> Added Trello - Nachos

- README.md
Adding new Mozilla desing system called Photon.
> Add Mozilla Photon Design System

- README.md
Adding recently open-sourced Ring Web UI components from JetBrains.
> Add JetBrains Ring UI

- README.md
Adding U.S. CMS.gov Design System in response to issue #58.
> Add U.S. CMS.gov Design System & Estonia Country Design Guidelines

- README.md
Modified the ReadMe.md to include the Predix Design System: www.predix-ui.com
> Add Predix Design System to list

- README.md
Just saw a new one that looks like it's pretty heavily used.
> Add City of Boston's design system

- README.md
The Photon Design System is the design system of Firefox and not Mozilla. For Mozilla design system see [https://mozilla.ninja/](https://mozilla.ninja/) ☺️
> Resolve #78

- README.md
Adding in the uSwitch style guide :)
> Adding in uStyle

- README.md
Add [Starbucks Style Guide](https://www.starbucks.com/static/reference/styleguide/) to `README.md`.
> Add Starbucks Style Guide

- README.md
Skin is eBay's CSS library and style system — [https://ebay.github.io/skin/](https://ebay.github.io/skin/)
> Adding eBay Style system 'Skin'

- README.md
Added UK Home Office design patterns and components to list, see more here https://home-office-digital-patterns.herokuapp.com/patterns
> update with Home Office design kit

- README.md
… it can be accessed here: https://primer.github.io/storybook/
> GitHub Primer supports storybook

- README.md
Add MongoDB Design System — http://mongodb.design
> Add MongoDB Design System

- README.md
[Monzo](https://monzo.com/) has recently published their [Tone of Voice](https://monzo.com/tone-of-voice/) guide.
> Add Monzo Tone of Voice guide

- README.md
- Main site is the GitHub Repo
- Component based
- Has both a StoryBook site and CodeSandeBox sandbox
> Add Pinterest Gestalt

- README.md
* Added emoji to mark the existence of a Designers Kit within the Morningstar Design System
> Added Designers Kit entry for the Morningstar Design System

- README.md
Using Material Theme Editor  - Sketch Plugin we can create Sketch Designers Kit
More info at https://material.io/tools/theme-editor/
So for Material Design - Its Yes | Yes | Yes | -
> Updated Material design with Designers Kit

- README.md
These are not yet in, but are coming up!
> remove components section from GitLab design system

- README.md
Hello! This PR adds Evergreen design system to the list.
Website: [evergreen.surge.sh](https://evergreen.surge.sh)
GitHub: [github.com/segmentio/evergreen](https://github.com/segmentio/evergreen)
> Add Evergreen

- README.md
- centering
- no punctuation for titles
> Nicery for the table

- README.md
wasn't sure what the spacing is for in the md file. lmk and i can update - thanks!
> adds base ui

- README.md
> adding zeit design system

- README.md
Changes should be made via PR's
> Remove link to create issue

- README.md
This one is interesting because it doesn't have components but it comes with the other aspects.
> chore: Add Finland Toolbox

- README.md
Added Flame design system by Banco Santander. 
Love your repo @alexpate !
> Add Flame 

- README.md
Add Fish Tank DS from Bloomberg BNA.
> feat: add Fish Tank Design System

- README.md
- Fixed: It has no code but it does have Designers kit
- Update: name
> Fix and Update Flame Design System Santander

- README.md
> Add Duolingo design system

- README.md
A library of typography, visual styles and user interface components which are documented for West Midlands Network.
Also contains our user research methods and voice/tone guide.
[West Midlands Network Design System](https://designsystem.wmnetwork.co.uk/)
> Add West Midlands Network Design System

- README.md
Add Decathlon Design System - Vitamin :tada:
> Added Decathlon
